name: stone_smart_flutter_example
description: Demonstrates how to use the stone_smart_flutter plugin.

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stone_smart_flutter:
    path: ../../stone_smart_flutter
  interface_stone_smart_flutter:
    path: ../../interface_stone_smart_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
